### ISSUE TITLE
Issue with pibooth-sound-effects 

### ISSUE THREAD

**Issue by breizho** [pibooth/pibooth-sound-effects#2]
Hello,

I do not understand this issue.
pibooth-sound-effects has beend installed sucessfully with pip3.

Pibooth has been lauched, and when I press the button to take a photo, I have:

[ DEBUG   ] pibooth           : +> took 0.181 seconds
Traceback (most recent call last):
  File "/home/pi/.local/bin/pibooth", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 439, in main
    app.main_loop()
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 361, in main_loop
    self._machine.process(events)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/states.py", line 66, in process
    self.set_state(new_state_name)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/states.py", line 94, in set_state
    hook(cfg=self.cfg, app=self.app, win=self.win)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/dist-packages/pibooth_sound_effects.py", line 48, in state_choose_enter
    app.sounds["button"].play()
KeyError: 'button'
pi@raspberrypi:~ $ 

Have you an idea ?
Thanks for your help,

Breizho

**Comment by werdeil** [comment]
Hi I just released a new version of the pluging (0.0.2) that could fix the issue, could you upgrade and tell me if you still have the issue?

`pip3 install -U pibooth-sound-effects`

**Comment by werdeil** [comment]
Hi I'm closing the issue as I think it is closed, feel free to reopen it if you still have it.
