### ISSUE TITLE
After install PiBooth won't start

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth-sound-effects#3]
After install i can't start PiBooth    ( I am stil using Raspbian GNU/Linux 9 (stretch) )
I have to uninstall "pibooth-sound-effects" to get PiBooth work again.

What am i doing wrong?

pibooth
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: picture-template-0.0.3, sound-effects-0.0.2, extra-lights-1.0.0
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.5/site-packages/pibooth/booth.py", line 422, in main
    plugin_manager.hook.pibooth_reset(cfg=config, hard=False)
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.5/site-packages/pibooth_sound_effects.py", line 28, in pibooth_reset
    shutil.copytree(source_sound_path, sound_path)
  File "/usr/lib/python3.5/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/lib/python3.5/site-packages/sounds'

**Comment by werdeil** [comment]
Hi,

Thanks for the feedback, this seems to be linked to the installation process (and the first copy of the sounds in the config folder), I need to rework on it. 

In the meantime if you want to use the plugin you can:
- Manually copy the `sounds` folder of this repository on your machine
- Write the path to this `sounds` folder in the `['SOUNDS']['sounds_path']` of your config file (run `pibooth --config` to open it).

I'll keep you informed as soon as I find a fix for this issue.

**Comment by DJ-Dingo** [comment]
Cool thanks, I'll just try that later.

I just updated to Raspberry Pi OS and it came up with some other bugs. When I get home to the other computer I can just post what it said, I saved a copy of it.

**Comment by werdeil** [comment]
I just pushed a fix, and released a new version on pip, tell me if version 0.0.3 solves the issue.

**Comment by DJ-Dingo** [comment]
Cool, Working Great. - I will make some new sounds in my sound studio soon :-)

Would it be possibel to have it play defriend sounds during the countdown, like --> 3.wav. 2.wav, 1.wav. ?

**Comment by werdeil** [comment]
For now it is not possible to have different sounds as the countdown is in the same state (so using the same sound).

But you can open a new issue (enhancement) and I'll try to find a way to handle it.
